---
title: "map_colors_function"
author: "Amanda Alker"
date: "4/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Let's look at the function

This is the function code from Barry's student

```{r}
#Old function
map.colors <- function (value,high.low,palette) {
  proportion <- ((value-high.low[1])/(high.low[2]-high.low[1]))
  index <- round ((length(palette)-1)*proportion)+1
  return (palette[index])
}
```
Now let's try to understand this function...

```{r}
map.colors2 <- function (x, 
                         high.low = range(x) , 
                         palette = cm.colors(100)) {
  
  #determine where in the 'high.low' range our values of 'x' lie
  percent <- ((x - high.low[1]) / (high.low[2] - high.low[1]))
  
  #Where in the 'palette' vector of colors is this 'percent' 
  # note catch for 0 percent values to 1
  index <- round ((length(palette) - 1) * percent) + 1
  
  return (palette[index])
}
```

##Working on our own functions

My first function
```{r}
add <- function(x, y=1) {
 # Sum the input x and y
 x + y
}
```

Let's test our first function
```{r}
add(x = 6, y = 4)
#dont have to use y=
```

```{r}
add( c(1:5, 20))
```

```{r}
#add(1, 3, 10)
# This will not work because the function add() only specified x and y
```

Write my 2nd function

```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

Test my 2nd function
```{r}
rescale(1:10)
```


```{r}
rescale( c(1,2,NA,3,10))
```

```{r}
rescale2 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  #allows NA to be considered 
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 if(na.rm) {
 rng <-range(x, na.rm=na.rm)
 } else {
 rng <-range(x)
 }
 print("Hello")
 
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
 print("is it me you are looking for?")

  if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 #does not print answer, instead prints
 print("I can see it in ...")
 
 #always at the end to get the entire output
 return(answer)
}
```

```{r}
rescale3( c(1,2,NA,3,10), plot = TRUE)
```

## Section 2B from Class 6

```{r}
library(bio3d)
#package is the journal that you need to go to the library to get those functions 
```


```{r}
library(bio3d)
#access the package

read.pdb("4AKE")
#command within package- retrieves information for this accession

s1 <- read.pdb("4AKE")
#assign object to this accession/action

s1$atom
#access atom column

s1$seqres
#access the residues for the protein

aa321(s1$seqres)
#extract the single letter AA code 

```

```{r}
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
#element type= CA- alpha carbon- central carbon- select just the #central atoms 

s1.chainA
#print to check
```

```{r}
s1.b <- s1.chainA$atom$b
#Access the b column of the output data
```

```{r}
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
```

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug

s2 <- read.pdb("1AKE") # kinase no drug

s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")

s2.chainA <- trim.pdb(s2, chain="A", elety="CA")

s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b

s2.b <- s2.chainA$atom$b

s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")

plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")

plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
s1 <- read.pdb("4AKE")
trim.pdb(s1, chain="A", elty="CA")
s1.b <- s1.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")

```

```{r}
read.pdb("string")
#read the input 
```



